#!/bin/bash

set -e

initialCwd=`pwd -P`

packagerPath=$0
builtin cd "`dirname "$packagerPath"`"
binDir=`basename "$packagerPath"`

# Detect node binary name
osName=`uname -s`
if [ "${osName:0:10}" == 'MINGW32_NT' ]; then
  nodeBin="node.exe"
else
  nodeBin="node"
fi

while [ -L "$binDir" ]
do
  binDir=`readlink "$binDir"`
  builtin cd "`dirname "$binDir"`"
  binDir=`basename "$binDir"`
done

binDir=`pwd -P`
builtin cd "$initialCwd"
"$binDir/$nodeBin" "$binDir/packager.js" "$@"
